Numpy

In [2]:
import numpy as np

In [14]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, "JECRC" , 34, 23.2])
print(arr)
print(arr[0:5])
print(arr[5:11])
print(type(arr))
print(arr.dtype)


['1' '2' '3' '4' '5' '6' '7' '8' '9' '10' 'JECRC' '34' '23.2']
['1' '2' '3' '4' '5']
['6' '7' '8' '9' '10' 'JECRC']
<class 'numpy.ndarray'>
<U32


In [29]:
print(arr[::-1])
print(arr[-5 : -2])
print(arr[9])

['23.2' '34' 'JECRC' '10' '9' '8' '7' '6' '5' '4' '3' '2' '1']
['9' '10' 'JECRC']
10


In [32]:
print(arr[-1:-3 : -1])

['23.2' '34']


In [34]:
arr.ndim  # 1D array = ndim

1

In [38]:
np.arange(23)


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22])

In [39]:
np.arange(1, 23, 2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21])

In [40]:
np.zeros(12)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [41]:
np.ones(12)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [43]:
np.linspace(1,5,10)  # 1 to 5 in 10 parts 

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

2D ARRAY

In [44]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [45]:
arr.ndim # 2D array = ndim

2

In [46]:
arr.shape

(3, 3)

In [52]:
arr[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [56]:
# [row,col]  [start:end, start:end]
print(arr[ 1:3, 1:3])

[[5 6]
 [8 9]]


In [58]:
arr[-1, -1]
arr[2][3]

9

In [60]:
np.arange(60)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [63]:
np.arange(60).reshape(12,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [59]:
np.arange(1, 13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [66]:
np.arange(60).reshape(12,5,1)

array([[[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4]],

       [[ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9]],

       [[10],
        [11],
        [12],
        [13],
        [14]],

       [[15],
        [16],
        [17],
        [18],
        [19]],

       [[20],
        [21],
        [22],
        [23],
        [24]],

       [[25],
        [26],
        [27],
        [28],
        [29]],

       [[30],
        [31],
        [32],
        [33],
        [34]],

       [[35],
        [36],
        [37],
        [38],
        [39]],

       [[40],
        [41],
        [42],
        [43],
        [44]],

       [[45],
        [46],
        [47],
        [48],
        [49]],

       [[50],
        [51],
        [52],
        [53],
        [54]],

       [[55],
        [56],
        [57],
        [58],
        [59]]])

In [75]:
# arr.ravel()
# arr.flatten()


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [76]:
np.random.randint(10)

6

In [79]:
np.random.randint(10, 100)

50

In [80]:
np.random.random(10)

array([0.44989796, 0.43059415, 0.57807416, 0.7127167 , 0.3122749 ,
       0.77016035, 0.87192443, 0.56397224, 0.44507113, 0.06810531])

In [81]:
np.random.random((10,3))

array([[0.94882761, 0.50394539, 0.34170209],
       [0.61052743, 0.36032949, 0.47447388],
       [0.56584476, 0.71579477, 0.0313382 ],
       [0.43997125, 0.19689882, 0.33664154],
       [0.69899775, 0.61425514, 0.57286935],
       [0.32271292, 0.48311275, 0.67334368],
       [0.79366886, 0.02823633, 0.32258042],
       [0.02214973, 0.96025886, 0.83520709],
       [0.07329428, 0.66181991, 0.76660164],
       [0.05735027, 0.66164681, 0.25190902]])

In [84]:
np.random.randint(1,5,10)

array([2, 4, 1, 2, 1, 3, 2, 2, 1, 2])

In [85]:
np.random.randint((1,5,10))

array([0, 3, 7])

In [88]:
arr2 = np.random.randint(1,5,10)
print(arr2)

[3 4 3 3 3 3 4 3 1 2]


In [89]:
arr2

array([3, 4, 3, 3, 3, 3, 4, 3, 1, 2])

In [90]:
arr2[-1] = 12

In [91]:
arr2

array([ 3,  4,  3,  3,  3,  3,  4,  3,  1, 12])

In [92]:
arr3 = np.random.randint(1,200,200)
arr3

array([ 16, 194, 191,  88, 117, 145, 148, 131,  17, 164, 148, 191,  98,
        67,  75, 174,  12,  78,  18, 152, 109,  86,  20, 104, 119,  23,
       185,  65, 141, 100,  68,  25,  31,  66, 155,  51,  38,  74, 191,
        93, 160, 153,   1,  36,  37,  78, 166, 115,  16,  66, 165,  59,
       151,  54,   3, 182,  80, 119, 124, 115, 100,  45,  69, 159, 121,
        25,  68,  71, 187, 114, 113, 192, 149,   1,  35, 124,  52,  11,
        33, 193,  14,  68, 107, 181,  72, 139,  94,  28, 127, 192,  16,
       153,  84,  99, 101, 133, 123, 127,  42,  41,  88, 154,  63,  98,
        66, 199,  70,  96, 123, 126, 105, 156,  20, 150,  95, 168,  83,
       120, 141, 194, 194, 198,   3,  25, 102, 192,  17,  12,   7,   2,
       139, 113, 131,   1, 199, 126,  48,  94,  62,  59,  47, 104, 194,
        52, 180,  21, 179, 145, 106, 156, 149,  16, 164,  49,  19,  89,
        86,   3,  52, 172, 197, 190, 170, 107,  44, 135,  37,  61,  88,
        76, 162,   8,  77,   4, 185, 140, 171, 191,   4, 174, 12

In [102]:
count = 0
for i in arr3 :
    if (i<100) :
        j = i
        count = count + 1    
        print(j)


print("Count :" ,count)

16
88
17
98
67
75
12
78
18
86
20
23
65
68
25
31
66
51
38
74
93
1
36
37
78
16
66
59
54
3
80
45
69
25
68
71
1
35
52
11
33
14
68
72
94
28
16
84
99
42
41
88
63
98
66
70
96
20
95
83
3
25
17
12
7
2
1
48
94
62
59
47
52
21
16
49
19
89
86
3
52
44
37
61
88
76
8
77
4
4
42
43
77
97
21
90
38
37
80
48
66
78
Count : 102


In [106]:
arr3[arr3<100].shape

(102,)