3Dimensional Array

In [1]:
import numpy as np

In [13]:
arr = np.full((3, 4, 5), 42)
print(arr)

[[[42 42 42 42 42]
  [42 42 42 42 42]
  [42 42 42 42 42]
  [42 42 42 42 42]]

 [[42 42 42 42 42]
  [42 42 42 42 42]
  [42 42 42 42 42]
  [42 42 42 42 42]]

 [[42 42 42 42 42]
  [42 42 42 42 42]
  [42 42 42 42 42]
  [42 42 42 42 42]]]


In [7]:
arr[1]

array([[42, 42, 42, 42, 42],
       [42, 42, 42, 42, 42],
       [42, 42, 42, 42, 42],
       [42, 42, 42, 42, 42]])

In [10]:
arr.ndim

3

In [14]:
arr[1]

array([[42, 42, 42, 42, 42],
       [42, 42, 42, 42, 42],
       [42, 42, 42, 42, 42],
       [42, 42, 42, 42, 42]])

In [16]:
arr[1:2:1]

array([[[42, 42, 42, 42, 42],
        [42, 42, 42, 42, 42],
        [42, 42, 42, 42, 42],
        [42, 42, 42, 42, 42]]])

In [17]:
arr[1,-1]

array([42, 42, 42, 42, 42])

In [18]:
arr[1,-1,2]

42

In [19]:
arr[::-1]

array([[[42, 42, 42, 42, 42],
        [42, 42, 42, 42, 42],
        [42, 42, 42, 42, 42],
        [42, 42, 42, 42, 42]],

       [[42, 42, 42, 42, 42],
        [42, 42, 42, 42, 42],
        [42, 42, 42, 42, 42],
        [42, 42, 42, 42, 42]],

       [[42, 42, 42, 42, 42],
        [42, 42, 42, 42, 42],
        [42, 42, 42, 42, 42],
        [42, 42, 42, 42, 42]]])

In [28]:
arr2 = np.array([[[1,2,3], 
                  [4,5,6],
                  [7,8,9],
                  [10,11,12]
                  ]],
                  )

print(arr2)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]]


In [29]:
arr[1]

array([[42, 42, 42, 42, 42],
       [42, 42, 42, 42, 42],
       [42, 42, 42, 42, 42],
       [42, 42, 42, 42, 42]])

In [31]:
arr[-1,2:4,]

array([[42, 42, 42, 42, 42],
       [42, 42, 42, 42, 42]])

In [32]:
arr[-1,2:4,2:4]

array([[42, 42],
       [42, 42]])

In [33]:
arr = np.random.randint(1, 100, (3, 4, 5))
print(arr)

[[[20 67 92 12 38]
  [51 84 97  8 81]
  [40 21 48  6 90]
  [85 98 62 41 60]]

 [[91 94  2 88  9]
  [22  6 22 49 96]
  [91 63 45 56  9]
  [48 79 46 14 60]]

 [[14 77 48 82 64]
  [90 57 45 63 23]
  [16 50 74 60 31]
  [89 45 31  9 52]]]


In [35]:
arr[-1,2:4,3:5]

array([[60, 31],
       [ 9, 52]])

In [37]:


arr = np.array([[[20, 67, 92, 12, 38],
                [51, 84, 97, 8, 81],
                [40, 21, 48, 6, 90],
                [85, 98, 62, 41, 60]],

               [[91, 94, 2, 88, 9],
                [22, 6, 22, 49, 96],
                [91, 63, 45, 56, 9],
                [48, 79, 46, 14, 60]],

               [[14, 77, 48, 82, 64],
                [90, 57, 45, 63, 23],
                [16, 50, 74, 60, 31],
                [89, 45, 31, 9, 52]]])
print(arr)

[[[20 67 92 12 38]
  [51 84 97  8 81]
  [40 21 48  6 90]
  [85 98 62 41 60]]

 [[91 94  2 88  9]
  [22  6 22 49 96]
  [91 63 45 56  9]
  [48 79 46 14 60]]

 [[14 77 48 82 64]
  [90 57 45 63 23]
  [16 50 74 60 31]
  [89 45 31  9 52]]]


In [38]:
arr[-1,2:4,3:5]

array([[60, 31],
       [ 9, 52]])

In [45]:
arr[0:3,0:1]

array([[[20, 67, 92, 12, 38]],

       [[91, 94,  2, 88,  9]],

       [[14, 77, 48, 82, 64]]])

In [47]:
arr[0:3,0:1,0:1]

array([[[20]],

       [[91]],

       [[14]]])

In [48]:
arr[-1,2:4,3:5]

array([[60, 31],
       [ 9, 52]])

In [53]:
arr[0:3,0:2,1:3]

array([[[67, 92],
        [84, 97]],

       [[94,  2],
        [ 6, 22]],

       [[77, 48],
        [57, 45]]])

In [55]:
arr4 =  np.random.randint(1,100,(4,5,5))
print(arr4)

[[[16 79 63 47 11]
  [39  2 10 59 68]
  [ 4 22 96 64 26]
  [71 81 40 36 33]
  [97 53 31 80 25]]

 [[47 20 31  3 52]
  [65 79 51 15 58]
  [93 79 31 25 98]
  [95  1 82 53 60]
  [59 60 11 70 60]]

 [[41 24 91 37 83]
  [38 67 78  6 45]
  [73 20 36 58 41]
  [26 85 85 43 44]
  [45 85 10 71 78]]

 [[50 19 11 71 29]
  [66 99 85  5 59]
  [43 79 94 37 12]
  [86 25  9 35 79]
  [90 13 45 49 39]]]


In [97]:
arr = np.random.randint(1,50, (4,5,5))
print(arr)

[[[ 7 20  9  3 48]
  [31 31  8 26 23]
  [39  3 23 36 29]
  [32 36 39 43  7]
  [32  2 12 10 45]]

 [[ 7 11  9 12 22]
  [ 7  8 47 12 16]
  [41 39  3 24 14]
  [38  1 38 27 12]
  [13 49 13  3 25]]

 [[26  8 48 46  1]
  [ 5 23 40  4 17]
  [ 9  9 37 17  4]
  [26 13  8 20 47]
  [ 1 43  1  1 28]]

 [[12 32 35  6 45]
  [47 48  5 30 25]
  [32 46 40 37 20]
  [40 26 37 24 15]
  [10 17 31 37 32]]]


In [81]:
print(arr.shape)

arr4.shape

(4, 5, 5)


(4, 5, 5)

In [98]:
arr3 = np.concatenate((arr, arr4), axis=1)

print(arr3)


[[[ 7 20  9  3 48]
  [31 31  8 26 23]
  [39  3 23 36 29]
  [32 36 39 43  7]
  [32  2 12 10 45]
  [16 79 63 47 11]
  [39  2 10 59 68]
  [ 4 22 96 64 26]
  [71 81 40 36 33]
  [97 53 31 80 25]]

 [[ 7 11  9 12 22]
  [ 7  8 47 12 16]
  [41 39  3 24 14]
  [38  1 38 27 12]
  [13 49 13  3 25]
  [47 20 31  3 52]
  [65 79 51 15 58]
  [93 79 31 25 98]
  [95  1 82 53 60]
  [59 60 11 70 60]]

 [[26  8 48 46  1]
  [ 5 23 40  4 17]
  [ 9  9 37 17  4]
  [26 13  8 20 47]
  [ 1 43  1  1 28]
  [41 24 91 37 83]
  [38 67 78  6 45]
  [73 20 36 58 41]
  [26 85 85 43 44]
  [45 85 10 71 78]]

 [[12 32 35  6 45]
  [47 48  5 30 25]
  [32 46 40 37 20]
  [40 26 37 24 15]
  [10 17 31 37 32]
  [50 19 11 71 29]
  [66 99 85  5 59]
  [43 79 94 37 12]
  [86 25  9 35 79]
  [90 13 45 49 39]]]


In [99]:
arr3+=3
print(arr3)

[[[ 10  23  12   6  51]
  [ 34  34  11  29  26]
  [ 42   6  26  39  32]
  [ 35  39  42  46  10]
  [ 35   5  15  13  48]
  [ 19  82  66  50  14]
  [ 42   5  13  62  71]
  [  7  25  99  67  29]
  [ 74  84  43  39  36]
  [100  56  34  83  28]]

 [[ 10  14  12  15  25]
  [ 10  11  50  15  19]
  [ 44  42   6  27  17]
  [ 41   4  41  30  15]
  [ 16  52  16   6  28]
  [ 50  23  34   6  55]
  [ 68  82  54  18  61]
  [ 96  82  34  28 101]
  [ 98   4  85  56  63]
  [ 62  63  14  73  63]]

 [[ 29  11  51  49   4]
  [  8  26  43   7  20]
  [ 12  12  40  20   7]
  [ 29  16  11  23  50]
  [  4  46   4   4  31]
  [ 44  27  94  40  86]
  [ 41  70  81   9  48]
  [ 76  23  39  61  44]
  [ 29  88  88  46  47]
  [ 48  88  13  74  81]]

 [[ 15  35  38   9  48]
  [ 50  51   8  33  28]
  [ 35  49  43  40  23]
  [ 43  29  40  27  18]
  [ 13  20  34  40  35]
  [ 53  22  14  74  32]
  [ 69 102  88   8  62]
  [ 46  82  97  40  15]
  [ 89  28  12  38  82]
  [ 93  16  48  52  42]]]


In [101]:
arr5 = np.random.randint(1,100,(3,4))
print(arr5)

[[54 46 36 53]
 [72  9 82 41]
 [93 94 32 49]]


In [102]:
arr6 = np.random.randint(1,100,(3,4))
print(arr6)
arr6.ndim

[[58 32 97 79]
 [69 39 35 24]
 [67 53 61 18]]


2

In [104]:
arr7 = arr5+arr6
print(arr7)


[[112  78 133 132]
 [141  48 117  65]
 [160 147  93  67]]


In [106]:
arr8 = np.random.randint(1,100,40)
print(arr8)

[ 5 43 14 94 95 38 67 73 78 34 49 98 41 18 57  9 83 25 41 69 86 32 75 76
 39 37 40 51 51  9 22 92 24 89 84 86 63 31 15 29]


In [113]:
np.sort(arr7)

array([[ 78, 112, 132, 133],
       [ 48,  65, 117, 141],
       [ 67,  93, 147, 160]])

In [117]:
np.sort(arr7, kind="mergesort")

array([[ 78, 112, 132, 133],
       [ 48,  65, 117, 141],
       [ 67,  93, 147, 160]])

In [118]:
arr7.min()

48

In [124]:
np.argmin(arr7)

5

In [130]:
print(arr7)
print(arr7.max())

r = np.argmax(arr7)
print(r)

[[112  78 133 132]
 [141  48 117  65]
 [160 147  93  67]]
160
8


In [131]:
arr8 = np.random.randint(1,100,40)
print(arr8)

[57 55 12 40 82 40  8 76 36 23 60 99 29 28 73 72 12 16 15 64 28 91 96 49
 22 11 76 20 98 94 68 27 93 50 33 17 91 88 53 31]


In [133]:
print(arr8)
print(arr8.max())

r = np.argmax(arr8)
print(r)

[57 55 12 40 82 40  8 76 36 23 60 99 29 28 73 72 12 16 15 64 28 91 96 49
 22 11 76 20 98 94 68 27 93 50 33 17 91 88 53 31]
99
11
